Name=input("Enter your name: ")
Branch=input("Enter your branch: ")
Gender=input("Enter your gender: ")
College=input("Enter College Name: ")
Age= int(input("Enter your age: "))
print("My name is:",Name)
print("Branch:",Branch)
print("Gender:",Gender)
print("College:", College)
print("Age:" ,Age)
